# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False, verbose_name='产品id')),
                ('name', models.CharField(max_length=100, verbose_name='产品名字')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='产品编号')),
                ('model', models.CharField(max_length=50, unique=True, verbose_name='产品型号')),
                ('classify', models.CharField(max_length=50, verbose_name='产品分类')),
                ('attribute', models.CharField(max_length=50, verbose_name='产品属性')),
                ('valuationMethod', models.CharField(max_length=50, verbose_name='计价方式')),
                ('checking', models.TextField(blank=True, verbose_name='质检方案')),
                ('baiscUnit', models.CharField(max_length=20, verbose_name='基本单位')),
                ('inclusionUnit', models.CharField(max_length=20, verbose_name='包含单位')),
                ('invoiceType', models.CharField(max_length=20, verbose_name='可开具发票类型')),
                ('tax', models.BooleanField(verbose_name='是否含税')),
                ('inventoryCeiling', models.IntegerField(default=0, verbose_name='库存上限')),
                ('lowerInventoryLimit', models.IntegerField(default=0, verbose_name='库存下限')),
                ('curingCycle', models.CharField(blank=True, max_length=10, verbose_name='养护周期')),
                ('failureLeadTime', models.CharField(blank=True, max_length=10, verbose_name='失效提前期')),
                ('mainSupplier', models.CharField(blank=True, max_length=40, verbose_name='主供应商')),
                ('lpercentage', models.FloatField(default=0, verbose_name='提成比例 （%）')),
                ('explain', models.TextField(blank=True, verbose_name='产品说明')),
                ('parameter', models.TextField(blank=True, verbose_name='产品参数')),
                ('appendix', models.CharField(blank=True, max_length=50, verbose_name='图片附件')),
                ('brand', models.CharField(max_length=20, verbose_name='品牌')),
                ('standard', models.TextField(verbose_name='规格')),
                ('usdOffer', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='USD报价')),
                ('mpq', models.IntegerField(default=0, verbose_name='MPQ')),
                ('unit', models.CharField(blank=True, max_length=10, verbose_name='单位')),
                ('ratio', models.FloatField(default=0, verbose_name='比例')),
                ('department', models.CharField(blank=True, max_length=20, verbose_name='部门')),
                ('barCode', models.CharField(blank=True, max_length=50, verbose_name='条形码')),
                ('adviseBid', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='建议进价')),
                ('topBid', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='最高进价')),
                ('adviseSprice', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='建议售价')),
                ('lowerSprice', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='最低售价')),
                ('index', models.IntegerField(default=0, verbose_name='搜索查看数')),
            ],
            options={
                'verbose_name': '物料库',
                'verbose_name_plural': '物料库',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(help_text='Example:172.25.0.0', max_length=30, unique=True, verbose_name='IP地址')),
                ('STATE', models.CharField(choices=[('down', '设备已关机'), ('up', '设备开机'), ('avi', '此IP未分配')], max_length=30, verbose_name='当前状态')),
                ('MODEL', models.CharField(blank=True, choices=[('fwq', '普通服务器'), ('gmszx', '高密四子星'), ('ups', 'UPS'), ('ccjd', '存储节点'), ('others', '其他')], max_length=30, verbose_name='型号')),
                ('IDD', models.CharField(blank=True, max_length=30, verbose_name='设备编号')),
                ('USER', models.CharField(blank=True, max_length=30, verbose_name='设备使用者')),
                ('TEL', models.CharField(blank=True, max_length=30, verbose_name='联系方式')),
                ('LOC', models.CharField(blank=True, max_length=30, verbose_name='设备位置')),
                ('NOTE', models.CharField(blank=True, max_length=30, verbose_name='备注')),
                ('TIME', models.DateTimeField(auto_now_add=True)),
                ('IPMI', models.CharField(blank=True, help_text='Example:172.25.0.0', max_length=30, unique=True, verbose_name='IPMI地址')),
            ],
            options={
                'verbose_name': 'IP',
                'verbose_name_plural': 'IP查询',
            },
        ),
    ]
