# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_delete_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='adviseBid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='建议进价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='adviseSprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='建议售价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='baiscUnit',
            field=models.CharField(blank=True, max_length=20, verbose_name='基本单位'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='inclusionUnit',
            field=models.CharField(blank=True, max_length=20, verbose_name='包含单位'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='lowerSprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='最低售价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='topBid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='最高进价'),
        ),
    ]
