# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20171128_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='mpq',
            field=models.IntegerField(blank=True, default=0, verbose_name='MPQ'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='usdOffer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='USD报价'),
        ),
    ]
