# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_goods'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
