# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='usdOffer',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='USD报价'),
        ),
    ]
