# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_auto_20171128_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(max_length=5, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='公司名字')),
                ('phone', models.CharField(max_length=20, verbose_name='公司电话')),
                ('email', models.CharField(max_length=20, verbose_name='公司邮箱')),
                ('address', models.CharField(max_length=50, verbose_name='公司地址')),
            ],
            options={
                'verbose_name': '公司信息',
                'verbose_name_plural': '公司信息',
            },
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['index'], 'verbose_name': '物料库', 'verbose_name_plural': '物料库'},
        ),
    ]
