# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_auto_20171130_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryInfo',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=20, verbose_name='客户姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='客户电话')),
                ('email', models.CharField(max_length=20, verbose_name='客户邮箱')),
                ('companyName', models.CharField(max_length=20, verbose_name='公司名称')),
                ('position', models.CharField(max_length=20, verbose_name='职位')),
                ('brand', models.CharField(max_length=20, verbose_name='品牌')),
                ('number', models.CharField(max_length=20, verbose_name='产品型号')),
                ('apply', models.CharField(max_length=100, verbose_name='应用')),
                ('describe', models.CharField(max_length=200, verbose_name='项目描述')),
                ('remark', models.CharField(max_length=200, verbose_name='备注')),
                ('isConduct', models.BooleanField(default=False, verbose_name='是否处理')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '询价申请',
                'verbose_name_plural': '询价申请',
                'ordering': ['-isConduct', 'dateTime'],
            },
        ),
    ]
