# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0017_auto_20171130_1519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
