# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0019_companyinfo_enquiryinfo_goods'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiryinfo',
            options={'ordering': ['-isConduct', '-dateTime'], 'verbose_name': '询价申请', 'verbose_name_plural': '询价申请'},
        ),
        migrations.RemoveField(
            model_name='goods',
            name='adviseBid',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='adviseSprice',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='barCode',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='curingCycle',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='department',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='failureLeadTime',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='inclusionUnit',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='lowerSprice',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='ratio',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='topBid',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='unit',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='qq',
            field=models.CharField(default='0', max_length=20, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='number',
            field=models.CharField(max_length=50, verbose_name='产品编号'),
        ),
    ]
