# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0020_auto_20171204_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='adviseBid',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='adviseSprice',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='barCode',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='curingCycle',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='department',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='failureLeadTime',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='inclusionUnit',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='lowerSprice',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='ratio',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='topBid',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='unit',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='qq',
            field=models.CharField(default='0', max_length=20, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='appendix',
            field=models.CharField(blank=True, max_length=200, verbose_name='图片附件'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='attribute',
            field=models.CharField(default='', max_length=50, verbose_name='产品属性'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='classify',
            field=models.CharField(default='', max_length=50, verbose_name='产品分类'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='invoiceType',
            field=models.CharField(default='其他', max_length=20, verbose_name='可开具发票类型'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='mainSupplier',
            field=models.CharField(blank=True, max_length=100, verbose_name='主供应商'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='model',
            field=models.CharField(max_length=50, verbose_name='产品型号'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='number',
            field=models.CharField(max_length=50, verbose_name='产品编号'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='standard',
            field=models.TextField(blank=True, verbose_name='规格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='tax',
            field=models.BooleanField(default=True, verbose_name='是否含税'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='valuationMethod',
            field=models.CharField(default='', max_length=50, verbose_name='计价方式'),
        ),
    ]
