# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0020_auto_20171210_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='standard',
            field=models.TextField(blank=True, verbose_name='规格'),
        ),
    ]
