# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0022_auto_20171210_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='model',
            field=models.CharField(max_length=50, verbose_name='产品型号'),
        ),
    ]
