# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0023_auto_20171210_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='attribute',
            field=models.CharField(default='', max_length=50, verbose_name='产品属性'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='classify',
            field=models.CharField(default='', max_length=50, verbose_name='产品分类'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='invoiceType',
            field=models.CharField(default='其他', max_length=20, verbose_name='可开具发票类型'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='valuationMethod',
            field=models.CharField(default='', max_length=50, verbose_name='计价方式'),
        ),
    ]
