# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0024_auto_20171210_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='mainSupplier',
            field=models.CharField(blank=True, max_length=100, verbose_name='主供应商'),
        ),
    ]
