# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-02 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0025_auto_20180501_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_link',
            field=models.CharField(default=2011, max_length=200, verbose_name='资讯链接'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='is_link',
            field=models.BooleanField(default=True, verbose_name='是否有链接'),
        ),
    ]
