# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0025_auto_20171210_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='appendix',
            field=models.CharField(blank=True, max_length=200, verbose_name='图片附件'),
        ),
    ]
