# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0026_auto_20171210_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='品牌'),
        ),
    ]
