# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-02 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0026_auto_20180502_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_link',
            field=models.CharField(blank=True, max_length=200, verbose_name='资讯链接'),
        ),
    ]
