# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-02 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0027_auto_20180502_0747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_time'], 'verbose_name': '资讯', 'verbose_name_plural': '资讯'},
        ),
    ]
