# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0028_auto_20180116_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycourse',
            name='year',
            field=models.IntegerField(verbose_name='年份'),
        ),
    ]
