# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0029_auto_20180116_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='valuationMethod',
        ),
    ]
