# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-03 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0030_remove_goods_valuationmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='postcode',
            field=models.CharField(default=518101, max_length=10, verbose_name='邮编'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='email',
            field=models.CharField(max_length=50, verbose_name='公司邮箱'),
        ),
    ]
