# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-24 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0032_auto_20180303_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='./upload/goods', verbose_name='图片'),
        ),
    ]
