# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-01 11:33
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0034_auto_20180501_0556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '资讯作者', 'verbose_name_plural': '资讯作者'},
        ),
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.TextField(default=1, verbose_name='摘要'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(verbose_name='内容'),
        ),
    ]
