# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-13 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0035_auto_20180501_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_time'], 'verbose_name': '资讯', 'verbose_name_plural': '资讯'},
        ),
        migrations.AddField(
            model_name='article',
            name='article_link',
            field=models.CharField(blank=True, max_length=200, verbose_name='资讯链接'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_link',
            field=models.BooleanField(default=True, verbose_name='是否有链接'),
        ),
    ]
