# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-30 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0036_auto_20180513_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='emailLink',
            field=models.CharField(default=1, max_length=100, verbose_name='邮箱系统'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='sysLink',
            field=models.CharField(default=1, max_length=100, verbose_name='内部系统'),
            preserve_default=False,
        ),
    ]
