# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-30 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0038_auto_20180730_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='emailLink',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='sysLink',
        ),
    ]
