# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-30 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0039_auto_20180730_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='emailLink',
            field=models.CharField(blank=True, max_length=100, verbose_name='邮箱系统'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='sysLink',
            field=models.CharField(blank=True, max_length=100, verbose_name='内部系统'),
        ),
    ]
