# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-30 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0041_auto_20180730_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='公司名字'),
        ),
    ]
