# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-30 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0046_auto_20180730_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': '公司信息', 'verbose_name_plural': '公司信息'},
        ),
    ]
