# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-11 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0030_auto_20180809_1650'),
        ('search', '0047_auto_20180730_1705'),
    ]

    operations = [
    ]
